[package]
name = "pii-masker-ri"
version = "0.1.0"
edition = "2021"
authors = ["Gianluca Brigandi <gbrigand@gmail.com>"]
description = "A tool to mask PII in source code using AST-based grepping and fake data generation."

[dependencies]
pii-masker-derive.workspace = true

